name: joerocks
favicon: null
layout_spectrum: 0.439515664242208
typography_spectrum: 0.4796235845424235
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5659921332262456
  lightness: 0.7333841905929148
  saturation: 0.05441396217793226
  rhythmicContrast: 0.26531215012073517
purpose: []
